name: raydium
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cycler=0.10.0
  - freetype=2.10.4
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libopenblas=0.3.13
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - pyparsing=2.4.7
  - python=3.9.4
  - python-dateutil=2.8.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
